plugins {
    id 'com.android.application'
}

android {
    namespace 'com.vaguer.virtualcamshizuku'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vaguer.virtualcamshizuku'
        minSdk 26
        targetSdk 35
        versionCode 12
        versionName '1.2.0'
    }

    buildFeatures {
        aidl true
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    implementation 'androidx.annotation:annotation:1.8.2'
}
